# Config file for `air` hot reload tool

[build]
  # Configurações de build
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  full_bin = "APP_ENV=development ./tmp/main"
  # Diretórios e arquivos a serem monitorados
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["README.md"]
  exclude_regex = ["_test.go"]
  # Diretórios e arquivos a serem monitorados para reiniciar o servidor
  watch_dir = ["."]
  watch_file = [".env"]

[log]
  # Configurações de log
  level = "debug"
  color = "true"
  timestamp = "true"

[dev]
  # Configurações de desenvolvimento
  cmd = "go run ./cmd/main.go"