// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"bbb-voting-service/internal/application/usecases"
	"bbb-voting-service/internal/infrastructure/consumer"
	"bbb-voting-service/internal/infrastructure/controllers"
	"bbb-voting-service/internal/infrastructure/producer"
	"bbb-voting-service/internal/infrastructure/repositories/postgres"
	repositories2 "bbb-voting-service/internal/infrastructure/repositories/redis"
	"bbb-voting-service/internal/infrastructure/services"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeContainer() (*Container, error) {
	db := InitDB()
	client := InitRedis()
	channel := InitRabbitMQ()
	postgresVoteRepository := repositories.NewPostgresVoteRepository(db)
	participantRepository := repositories.NewParticipantRepository(db)
	redisRepository := repositories2.NewRedisRepository(client)
	rabbitMQProducer := queue.NewRabbitMQProducer(channel)
	processVoteUsecase := usecase.NewProcessVoteUsecase(postgresVoteRepository, participantRepository)
	castVoteUsecase := usecase.NewCastVoteUsecase(redisRepository, rabbitMQProducer, participantRepository)
	createParticipantUsecase := usecase.NewCreateParticipantUsecase(participantRepository)
	getParticipantsUsecase := usecase.NewGetParticipantsUsecase(participantRepository)
	deleteParticipantUsecase := usecase.NewDeleteParticipantUsecase(participantRepository)
	getParticipantUsecase := usecase.NewGetParticipantUsecase(participantRepository)
	getPartialResultsUsecase := usecase.NewGetPartialResultsUsecase(redisRepository)
	getFinalResultsUsecase := usecase.NewGetFinalResultsUseCase(postgresVoteRepository)
	captchaService := services.NewCaptchaService()
	captchaController := controllers.NewCaptchaController(captchaService)
	participantController := controllers.NewParticipantController(getParticipantsUsecase, getParticipantUsecase, createParticipantUsecase, deleteParticipantUsecase)
	voteController := controllers.NewVoteController(castVoteUsecase)
	resultController := controllers.NewResultController(getPartialResultsUsecase, getFinalResultsUsecase)
	rabbitMQConsumer := consumer.NewRabbitMQConsumer(channel, processVoteUsecase)
	container := &Container{
		DB:                       db,
		RedisClient:              client,
		RabbitMQChannel:          channel,
		VoteRepository:           postgresVoteRepository,
		ParticipantRepository:    participantRepository,
		RedisRepository:          redisRepository,
		RabbitMQRepository:       rabbitMQProducer,
		ProcessVoteUsecase:       processVoteUsecase,
		CastVoteUsecase:          castVoteUsecase,
		CreateParticipantUsecase: createParticipantUsecase,
		GetParticipantsUsecase:   getParticipantsUsecase,
		DeleteParticipantUsecase: deleteParticipantUsecase,
		GetParticipantUsecase:    getParticipantUsecase,
		GetPartialResultsUsecase: getPartialResultsUsecase,
		GetFinalResultsUseCase:   getFinalResultsUsecase,
		CaptchaService:           captchaService,
		CaptchaController:        captchaController,
		ParticipantController:    participantController,
		VoteController:           voteController,
		ResultController:         resultController,
		RabbitMQConsumer:         rabbitMQConsumer,
	}
	return container, nil
}
